//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsApp1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int IntervaloAtualizacao {
            get {
                return ((int)(this["IntervaloAtualizacao"]));
            }
            set {
                this["IntervaloAtualizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IniciarWindows {
            get {
                return ((bool)(this["IniciarWindows"]));
            }
            set {
                this["IniciarWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TransparenciaPrincipal {
            get {
                return ((int)(this["TransparenciaPrincipal"]));
            }
            set {
                this["TransparenciaPrincipal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TransparenciaGrafico {
            get {
                return ((int)(this["TransparenciaGrafico"]));
            }
            set {
                this["TransparenciaGrafico"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.85")]
        public float OpacidadePadrao {
            get {
                return ((float)(this["OpacidadePadrao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float OpacidadeFoco {
            get {
                return ((float)(this["OpacidadeFoco"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CpuHabilitadaPrincipal {
            get {
                return ((bool)(this["CpuHabilitadaPrincipal"]));
            }
            set {
                this["CpuHabilitadaPrincipal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GpuHabilitadaPrincipal {
            get {
                return ((bool)(this["GpuHabilitadaPrincipal"]));
            }
            set {
                this["GpuHabilitadaPrincipal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RamHabilitadaPrincipal {
            get {
                return ((bool)(this["RamHabilitadaPrincipal"]));
            }
            set {
                this["RamHabilitadaPrincipal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CpuHabilitadaGraficoUsoGeral {
            get {
                return ((bool)(this["CpuHabilitadaGraficoUsoGeral"]));
            }
            set {
                this["CpuHabilitadaGraficoUsoGeral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GpuHabilitadaGraficoUsoGeral {
            get {
                return ((bool)(this["GpuHabilitadaGraficoUsoGeral"]));
            }
            set {
                this["GpuHabilitadaGraficoUsoGeral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RamHabilitadaGraficoUsoGeral {
            get {
                return ((bool)(this["RamHabilitadaGraficoUsoGeral"]));
            }
            set {
                this["RamHabilitadaGraficoUsoGeral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int UnidadesEixoXGraficoUsoGeral {
            get {
                return ((int)(this["UnidadesEixoXGraficoUsoGeral"]));
            }
            set {
                this["UnidadesEixoXGraficoUsoGeral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int IntervaloAtualizacaoGraficoUsoGeral {
            get {
                return ((int)(this["IntervaloAtualizacaoGraficoUsoGeral"]));
            }
            set {
                this["IntervaloAtualizacaoGraficoUsoGeral"] = value;
            }
        }
    }
}
